/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendreRouteImport } from './routes/vendre'
import { Route as PolitiqueRgpdRouteImport } from './routes/politique-rgpd'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LouerRouteImport } from './routes/louer'
import { Route as HonorairesRouteImport } from './routes/honoraires'
import { Route as DernieresVentesRouteImport } from './routes/dernieres-ventes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcheterRouteImport } from './routes/acheter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnoncesIndexRouteImport } from './routes/annonces.index'
import { Route as AnnoncesIdRouteImport } from './routes/annonces.$id'

const VendreRoute = VendreRouteImport.update({
  id: '/vendre',
  path: '/vendre',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueRgpdRoute = PolitiqueRgpdRouteImport.update({
  id: '/politique-rgpd',
  path: '/politique-rgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LouerRoute = LouerRouteImport.update({
  id: '/louer',
  path: '/louer',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorairesRoute = HonorairesRouteImport.update({
  id: '/honoraires',
  path: '/honoraires',
  getParentRoute: () => rootRouteImport,
} as any)
const DernieresVentesRoute = DernieresVentesRouteImport.update({
  id: '/dernieres-ventes',
  path: '/dernieres-ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcheterRoute = AcheterRouteImport.update({
  id: '/acheter',
  path: '/acheter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIndexRoute = AnnoncesIndexRouteImport.update({
  id: '/annonces/',
  path: '/annonces/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIdRoute = AnnoncesIdRouteImport.update({
  id: '/annonces/$id',
  path: '/annonces/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acheter': typeof AcheterRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dernieres-ventes': typeof DernieresVentesRoute
  '/honoraires': typeof HonorairesRoute
  '/louer': typeof LouerRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-rgpd': typeof PolitiqueRgpdRoute
  '/vendre': typeof VendreRoute
  '/annonces/$id': typeof AnnoncesIdRoute
  '/annonces/': typeof AnnoncesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acheter': typeof AcheterRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dernieres-ventes': typeof DernieresVentesRoute
  '/honoraires': typeof HonorairesRoute
  '/louer': typeof LouerRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-rgpd': typeof PolitiqueRgpdRoute
  '/vendre': typeof VendreRoute
  '/annonces/$id': typeof AnnoncesIdRoute
  '/annonces': typeof AnnoncesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acheter': typeof AcheterRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dernieres-ventes': typeof DernieresVentesRoute
  '/honoraires': typeof HonorairesRoute
  '/louer': typeof LouerRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-rgpd': typeof PolitiqueRgpdRoute
  '/vendre': typeof VendreRoute
  '/annonces/$id': typeof AnnoncesIdRoute
  '/annonces/': typeof AnnoncesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acheter'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dernieres-ventes'
    | '/honoraires'
    | '/louer'
    | '/mentions-legales'
    | '/politique-rgpd'
    | '/vendre'
    | '/annonces/$id'
    | '/annonces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acheter'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dernieres-ventes'
    | '/honoraires'
    | '/louer'
    | '/mentions-legales'
    | '/politique-rgpd'
    | '/vendre'
    | '/annonces/$id'
    | '/annonces'
  id:
    | '__root__'
    | '/'
    | '/acheter'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dernieres-ventes'
    | '/honoraires'
    | '/louer'
    | '/mentions-legales'
    | '/politique-rgpd'
    | '/vendre'
    | '/annonces/$id'
    | '/annonces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcheterRoute: typeof AcheterRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DernieresVentesRoute: typeof DernieresVentesRoute
  HonorairesRoute: typeof HonorairesRoute
  LouerRoute: typeof LouerRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueRgpdRoute: typeof PolitiqueRgpdRoute
  VendreRoute: typeof VendreRoute
  AnnoncesIdRoute: typeof AnnoncesIdRoute
  AnnoncesIndexRoute: typeof AnnoncesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendre': {
      id: '/vendre'
      path: '/vendre'
      fullPath: '/vendre'
      preLoaderRoute: typeof VendreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-rgpd': {
      id: '/politique-rgpd'
      path: '/politique-rgpd'
      fullPath: '/politique-rgpd'
      preLoaderRoute: typeof PolitiqueRgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/louer': {
      id: '/louer'
      path: '/louer'
      fullPath: '/louer'
      preLoaderRoute: typeof LouerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honoraires': {
      id: '/honoraires'
      path: '/honoraires'
      fullPath: '/honoraires'
      preLoaderRoute: typeof HonorairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dernieres-ventes': {
      id: '/dernieres-ventes'
      path: '/dernieres-ventes'
      fullPath: '/dernieres-ventes'
      preLoaderRoute: typeof DernieresVentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acheter': {
      id: '/acheter'
      path: '/acheter'
      fullPath: '/acheter'
      preLoaderRoute: typeof AcheterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/': {
      id: '/annonces/'
      path: '/annonces'
      fullPath: '/annonces/'
      preLoaderRoute: typeof AnnoncesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/$id': {
      id: '/annonces/$id'
      path: '/annonces/$id'
      fullPath: '/annonces/$id'
      preLoaderRoute: typeof AnnoncesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcheterRoute: AcheterRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DernieresVentesRoute: DernieresVentesRoute,
  HonorairesRoute: HonorairesRoute,
  LouerRoute: LouerRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueRgpdRoute: PolitiqueRgpdRoute,
  VendreRoute: VendreRoute,
  AnnoncesIdRoute: AnnoncesIdRoute,
  AnnoncesIndexRoute: AnnoncesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
