/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendreRouteImport } from './routes/vendre'
import { Route as LouerRouteImport } from './routes/louer'
import { Route as DernieresVentesRouteImport } from './routes/dernieres-ventes'
import { Route as AnnoncesRouteImport } from './routes/annonces'
import { Route as AcheterRouteImport } from './routes/acheter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnoncesIdRouteImport } from './routes/annonces.$id'

const VendreRoute = VendreRouteImport.update({
  id: '/vendre',
  path: '/vendre',
  getParentRoute: () => rootRouteImport,
} as any)
const LouerRoute = LouerRouteImport.update({
  id: '/louer',
  path: '/louer',
  getParentRoute: () => rootRouteImport,
} as any)
const DernieresVentesRoute = DernieresVentesRouteImport.update({
  id: '/dernieres-ventes',
  path: '/dernieres-ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesRoute = AnnoncesRouteImport.update({
  id: '/annonces',
  path: '/annonces',
  getParentRoute: () => rootRouteImport,
} as any)
const AcheterRoute = AcheterRouteImport.update({
  id: '/acheter',
  path: '/acheter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIdRoute = AnnoncesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnnoncesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acheter': typeof AcheterRoute
  '/annonces': typeof AnnoncesRouteWithChildren
  '/dernieres-ventes': typeof DernieresVentesRoute
  '/louer': typeof LouerRoute
  '/vendre': typeof VendreRoute
  '/annonces/$id': typeof AnnoncesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acheter': typeof AcheterRoute
  '/annonces': typeof AnnoncesRouteWithChildren
  '/dernieres-ventes': typeof DernieresVentesRoute
  '/louer': typeof LouerRoute
  '/vendre': typeof VendreRoute
  '/annonces/$id': typeof AnnoncesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acheter': typeof AcheterRoute
  '/annonces': typeof AnnoncesRouteWithChildren
  '/dernieres-ventes': typeof DernieresVentesRoute
  '/louer': typeof LouerRoute
  '/vendre': typeof VendreRoute
  '/annonces/$id': typeof AnnoncesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acheter'
    | '/annonces'
    | '/dernieres-ventes'
    | '/louer'
    | '/vendre'
    | '/annonces/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acheter'
    | '/annonces'
    | '/dernieres-ventes'
    | '/louer'
    | '/vendre'
    | '/annonces/$id'
  id:
    | '__root__'
    | '/'
    | '/acheter'
    | '/annonces'
    | '/dernieres-ventes'
    | '/louer'
    | '/vendre'
    | '/annonces/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcheterRoute: typeof AcheterRoute
  AnnoncesRoute: typeof AnnoncesRouteWithChildren
  DernieresVentesRoute: typeof DernieresVentesRoute
  LouerRoute: typeof LouerRoute
  VendreRoute: typeof VendreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendre': {
      id: '/vendre'
      path: '/vendre'
      fullPath: '/vendre'
      preLoaderRoute: typeof VendreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/louer': {
      id: '/louer'
      path: '/louer'
      fullPath: '/louer'
      preLoaderRoute: typeof LouerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dernieres-ventes': {
      id: '/dernieres-ventes'
      path: '/dernieres-ventes'
      fullPath: '/dernieres-ventes'
      preLoaderRoute: typeof DernieresVentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces': {
      id: '/annonces'
      path: '/annonces'
      fullPath: '/annonces'
      preLoaderRoute: typeof AnnoncesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acheter': {
      id: '/acheter'
      path: '/acheter'
      fullPath: '/acheter'
      preLoaderRoute: typeof AcheterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/$id': {
      id: '/annonces/$id'
      path: '/$id'
      fullPath: '/annonces/$id'
      preLoaderRoute: typeof AnnoncesIdRouteImport
      parentRoute: typeof AnnoncesRoute
    }
  }
}

interface AnnoncesRouteChildren {
  AnnoncesIdRoute: typeof AnnoncesIdRoute
}

const AnnoncesRouteChildren: AnnoncesRouteChildren = {
  AnnoncesIdRoute: AnnoncesIdRoute,
}

const AnnoncesRouteWithChildren = AnnoncesRoute._addFileChildren(
  AnnoncesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcheterRoute: AcheterRoute,
  AnnoncesRoute: AnnoncesRouteWithChildren,
  DernieresVentesRoute: DernieresVentesRoute,
  LouerRoute: LouerRoute,
  VendreRoute: VendreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
